"""Sales & Marketing — turn a script into a pitch deck and market analysis."""

import io
import re
import xml.etree.ElementTree as ET

import streamlit as st
from fpdf import FPDF

from portal_auth import require_login, portal_header
from ai_utils import ai_ready, generate_content

try:
    from pypdf import PdfReader
except ImportError:                       # pragma: no cover
    from PyPDF2 import PdfReader

try:
    from gtts import gTTS
    HAS_TTS = True
except ImportError:
    HAS_TTS = False

st.set_page_config(page_title="Sales & Marketing", page_icon="📈", layout="wide")
require_login()
portal_header("📈 Sales & Marketing",
              "Upload a .pdf or .fdx script to generate a pitch deck: logline, "
              "audience, budget-aware comparables and franchise angles.")

AI_READY = ai_ready()


def extract_text(upload) -> str:
    if upload.name.lower().endswith(".pdf"):
        reader = PdfReader(upload)
        return "\n".join((p.extract_text() or "") for p in reader.pages)
    tree = ET.parse(upload)
    root = tree.getroot()
    parts = []
    for para in root.findall(".//Paragraph"):
        t = "".join(n.text for n in para.findall(".//Text") if n.text).strip()
        if t:
            parts.append(t)
    return "\n".join(parts)


c1, c2, c3 = st.columns(3)
with c1:
    uploaded = st.file_uploader("1. Script (.pdf or .fdx)", type=["pdf", "fdx"])
with c2:
    budget = st.selectbox("2. Budget tier",
                          ["Micro-Budget (under £250k)", "Indie (£1M–£5M)",
                           "Studio Feature (£15M+)"])
    character = st.text_input("3. Franchise character", "e.g. JOHN")
with c3:
    ip_owner = st.text_input("4. Project / studio name", "STUDENT PROJECT")

if st.button("🚀 Generate pitch deck", type="primary", use_container_width=True):
    if uploaded is None:
        st.error("Upload a script file first.")
    elif not character or character == "e.g. JOHN":
        st.warning("Enter the character you hold franchise rights to.")
    elif not AI_READY:
        st.error("AI is not configured. Add a GEMINI_API_KEY in the app's "
                 "Secrets to use this module.")
    else:
        with st.spinner("Analysing the script and building the deck…"):
            name_clean = uploaded.name.replace(".fdx", "").replace(".pdf", "")
            sample = extract_text(uploaded)[:60000]
            prompt = f"""You are a film sales agent and studio executive.
From the script text, produce a pitch deck and market analysis.
Budget tier: {budget}. Franchise rights are held only for character
{character.upper()}. Use Markdown with these sections:

## 1. Logline & Elevator Pitch
One-sentence logline, then a 3-sentence elevator pitch.

## 2. Target Demographic
Primary audience (age, gender, interests); is it four-quadrant, and who buys
tickets opening weekend?

## 3. Comparable Films
Three successful films within or close to the {budget} range. For each:
- Title (Year)
- Budget vs box office
- Why it's comparable (ROI viability)

## 4. Franchise Potential ({character.upper()})
Two viable spin-off or franchise ideas based only on {character.upper()}.

---
PDF_SUMMARY: a punchy 3-paragraph executive summary (logline, demographic, comps).
---
PITCH_PROMPTS: three vivid English image-generator prompts for cinematic movie
posters, on one line separated by | .

Script sample:
{sample}"""
            analysis, pdf_summary, prompts, audio = "", "", [], None
            try:
                body = generate_content(prompt)
                if "PITCH_PROMPTS:" in body:
                    body, tail = body.split("PITCH_PROMPTS:", 1)
                    prompts = [p.strip() for p in tail.split("|") if p.strip()]
                if "PDF_SUMMARY:" in body:
                    analysis, pdf_summary = [s.strip()
                                             for s in body.split("PDF_SUMMARY:", 1)]
                else:
                    analysis = pdf_summary = body.strip()

                if HAS_TTS:
                    try:
                        clean = re.sub(r"[*_#]", "", pdf_summary)
                        buf = io.BytesIO()
                        gTTS(text=clean, lang="en").write_to_fp(buf)
                        buf.seek(0)
                        audio = buf
                    except Exception:
                        audio = None
            except Exception as e:
                analysis = pdf_summary = f"AI error: {e}"

            st.success(f"Pitch deck generated for **{name_clean}**.")
            st.caption(f"Project: {ip_owner.upper()} — generated by the "
                       "P.A.C.E. pitch engine")
            st.divider()
            if audio:
                st.audio(audio, format="audio/mp3")
            st.markdown(analysis)

            if prompts:
                st.divider()
                st.subheader("🎨 Movie-poster prompts")
                st.caption("Paste into your image generator (2:3 poster ratio "
                           "appended):")
                for p in prompts:
                    st.code(f"{p} --ar 2:3", language="text")

            # --- PDF export ---
            class PitchPDF(FPDF):
                def header(self):
                    self.set_fill_color(20, 20, 20)
                    self.rect(0, 0, 210, 297, "F")
                    self.set_text_color(200, 200, 200)
                    self.set_font("Arial", "B", 10)
                    self.cell(0, 10, f"PITCH DECK | {ip_owner.upper()}",
                              ln=True, align="R")
                    self.ln(4)

            def san(t):
                return (str(t).replace("•", "-").replace("€", "EUR ")
                        .replace("£", "GBP ").replace("’", "'").replace("“", '"')
                        .replace("”", '"').encode("latin-1", "replace")
                        .decode("latin-1"))

            pdf = PitchPDF()
            pdf.add_page()
            pdf.set_text_color(255, 255, 255)
            pdf.set_font("Arial", "B", 22)
            pdf.cell(0, 14, san(f"PROJECT: {name_clean.upper()}"), ln=True,
                     align="C")
            pdf.set_font("Arial", "I", 13)
            pdf.set_text_color(0, 229, 255)
            pdf.cell(0, 10, san(f"Budget tier: {budget}"), ln=True, align="C")
            pdf.ln(8)
            pdf.set_font("Arial", "", 11)
            pdf.set_text_color(220, 220, 220)
            clean = pdf_summary.replace("**", "").replace("##", "") \
                               .replace("#", "").replace("---", "")
            pdf.multi_cell(0, 6, san(clean))
            out = pdf.output(dest="S")
            data = out.encode("latin-1") if isinstance(out, str) else bytes(out)

            st.divider()
            st.download_button("📥 Download pitch deck (.pdf)", data,
                               file_name=f"Pitch_{name_clean}.pdf",
                               mime="application/pdf", use_container_width=True)
